### ISSUE TITLE
Provider instance of @effector/next can't be reached in next.js app

### ISSUE THREAD

**Issue by InkyQuill** [effector/next#18] opened 2023-08-02 14:30 UTC
project deps:
- effector: 22.8.6
- effector-react: 22.5.3
- @effector/next : 0.5.1
- next: 13.4.12
- react: 18.2.0

App router.

if I use `<EffectorNext>` in my app, all useUnit / useStore / useGate and everything else can't see the effector-react Provider. The error from nextjs is: `Error: No scope found, consider adding <Provider> to app root`.

I took the actual code from the repo and placed it into my project, `<EffectorNext>` started working as a provider. There is also a same issue mentioned on effector github: https://github.com/effector/effector/issues/727

**Comment by Eugene2115** [comment] 2023-08-03 13:04
Do you have reactSsr flag in your effector/babel-plugin config ? If so, try to remove it.

**Comment by AlexandrHoroshih** [comment] 2023-08-04 07:37
Hi @InkyQuill !

Could you share an reporduce? 🤔 
Also, how does your babel-plugin configuration looks like?

There are few examples in the docs on plugin configuration
https://github.com/effector/next#babel-plugin
https://github.com/effector/next#dont-forget-about-use-client-for-client-components

Just in case:
`effector-react/scope` and `reactSsr` option are legacy and will be deprecated in the next major release of effector - `@effector/next` (and latest version of `nextjs-effector` which is built on top of it) are not using these APIs and are not recommending them in the documentation

**Comment by InkyQuill** [comment] 2023-08-07 08:08
Hello. I've removed my hack, removed reactSsr from the .babelrc file, and still have the same error: `Error: No scope found, consider adding <Provider> to app root`. I'll try to make a reproduction as the project with this error is confidential.

**Comment by AlexandrHoroshih** [comment] 2023-08-27 13:27
@InkyQuill Hello!

Any news on the reproduction? 🙏

**Comment by AlexandrHoroshih** [comment] 2023-09-07 06:00
It is not possible to address the issue without the reproduce, so i will close it 😢

**Closed as completed by AlexandrHoroshih** 2023-09-07 06:00 UTC
